### ISSUE TITLE
Review naming an update where needed

### ISSUE THREAD

**Issue by MisterJimson** [HomeXLabs/optimizely-dart#2]
For example: https://github.com/HomeXLabs/optimizely-dart/blob/3082f9d30421406c71d85fa98f36029dd29caa74/pubspec.yaml#L23

**Comment by MisterJimson** [comment]
We probably want this changed as well: https://github.com/HomeXLabs/optimizely-dart/blob/3082f9d30421406c71d85fa98f36029dd29caa74/pubspec.yaml#L23

**Comment by ubbop42** [comment]
resolved
